### ISSUE TITLE
Error in Chords o7, M6 and m6 when transposed

### ISSUE THREAD

**Issue by vellebelle** [tonaljs/tonal#100]
**Describe the bug**
It seems that there is a problem with the three chords o7, M6 and m6. When getting the notes for o7 and M6, the last note (diminished 7th and the 6th note, respectively) are an octave higher than they should be. The m6 also has the 6th an octave too high, but also an extra note added to it (the 4th - This is BTW related to issue #97 ).

**Behavior**
```
Chord.intervals('o7').map(transpose('C3')); // ["C3", "Eb3", "Gb3", "A4"]
Chord.intervals('M6').map(transpose('C3')); // ["C3", "E3", "G3", "A4"]
Chord.intervals('m6').map(transpose('C3')); // ["C3", "Eb3", "F3", "G3", "A4"]
```

**Expected behavior**
```
Chord.intervals('o7').map(transpose('C3')); // ["C3", "Eb3", "Gb3", "A3"]
Chord.intervals('M6').map(transpose('C3')); // ["C3", "E3", "G3", "A3"]
Chord.intervals('m6').map(transpose('C3')); // ["C3", "Eb3", "G3", "A3"]
```

**Video**
I have recorded a short screencast showing the problem: 
https://www.dropbox.com/s/bnbn2o3zg5yhpqz/error-in-chords.mp4?dl=0

**Comment by danigb** [comment]
Thanks for the detailed explanation! 👍 

It's fixed in an upcoming release. Take a look to: https://github.com/danigb/tonal/tree/feat/v3
