### ISSUE TITLE
Lydian #9 scale includes b9 instead of #9

### ISSUE THREAD

**Issue by Euthymious** [tonaljs/tonal#101]
**To Reproduce**
Tonal.Scale.notes("C lydian #9") => ["C", "Db", "E", "F#", "G", "A", "B"]

**Expected behavior**
Tonal.Scale.notes("C lydian #9") => ["C", "D#", "E", "F#", "G", "A", "B"]

**Comment by danigb** [comment]
Thanks for reporting!! 👍 

Fixed in an upcoming release. Take a look to: https://github.com/danigb/tonal/tree/feat/v3
