### ISSUE TITLE
Minified version not available anymore 

### ISSUE THREAD

**Issue by mattiasu96** [tonaljs/tonal#104]
The minified version of the library is not available anymore at the link given at Npm: https://github.com/tonaljs/tonal/blob/master/dist/tonal.min.js

Following the link will give an error 404, also the demo provided in the npm website doesn't work anymore because of the missing link (you can check the error 404 in the console log once you try to load the demo)

**Comment by danigb** [comment]
Yes, currently there's no package that includes the whole library and I don't know if it will be or how... Meanwhile, you can use v2: https://github.com/tonaljs/v2/blob/master/dist/tonal.min.js
