### ISSUE TITLE
Programmatically add scales to dictionary?

### ISSUE THREAD

**Issue by bloom510** [tonaljs/tonal#105]
I'm working with some scales not found in the dictionary (primarily Messiaen's [third mode of limited transposition](https://en.wikipedia.org/wiki/Modes_of_limited_transposition)) and I'm wondering if it's possible to programmatically add them from Tonal. If not, could it be added to the dictionary? Thanks!

**Comment by danigb** [comment]
Hi! I'll be happy to include them 👌. Take a look to the file where all scales are defined (a. .json file inside scale-dictionary package) and open a PR with the changes. We can continue de conversation there 👍

**Comment by danigb** [comment]
Now you can:

```js
import { addScale } from '@tonaljs/scale-dictionary'
import { scale } from '@tonaljs/scale'
addScale(["1P", "2M", ...], "Messiaen's first mode");
scale("C Maessian's first mode") // => { notes: ["C", "D", ... }
```

Hope it helps
