### ISSUE TITLE
Types not found

### ISSUE THREAD

**Issue by cannoneyed** [tonaljs/tonal#107]
There seems to be a small issue with the new v3 release, where the types aren't being properly linked in each module's package.json. The release "types" field points to `dist/index.d.ts`, but the typing file is actually located in `dist/tonal/index.d.ts`.

**Comment by danigb** [comment]
I'm afraid you're right. I'm currently on vacations, but I will fix it as soon as I come back

**Comment by cannoneyed** [comment]
Thanks! No rush, and I'd open up a PR if it weren't a build thing

**Comment by danigb** [comment]
I've just published a new 3.2.2 version with correct types path.
