### ISSUE TITLE
What happened to tonal.range.chromatic?

### ISSUE THREAD

**Issue by sustained** [tonaljs/tonal#110]
I found this in an issue from 2017, when I searched for "chromatic":

```js
tonal.range.chromatic('C4, F4, D4') // => [ 'C4', 'Db4', 'D4', 'Eb4', 'E4', 'F4', 'E4', 'Eb4', 'D4' ]
```

I need to generate chromatic ranges for my sample loader so I know which samples to load e.g. -

```js
export const SAMPLE_RANGES = {
  piano: ["A0", "G#6"], // A0.mp3, Bb0.mp3, B0.mp3, C1.mp3, ...
  cello: ["A2", "G#4"],
  violin: ["A3", "G6"]
}
```

I could do it myself but surely this library can help me to achieve that?

But I looked at the docs for all the new packages in v3 and none of them seem to have anything for chromatic ranges.

I found this on NPM (https://github.com/danigb/tonal/extensions/range) but the link is dead.

:frowning_face:

**Comment by sustained** [comment]
I just made my own version using `note`, `enharmonic` and `transpose`, `note(...).height` and a loop but I'd rather use yours if it exists. If it doesn't consider this a feature request.

It's kind of odd though, you'll get things like `Ebb1` and other nonsense if you keep transposing by minor seconds so you need to use `enharmonic`.

**Comment by danigb** [comment]
You're right. Working on this. Expect `range` package to come back soon. 👍

Thanks for reporting 👌

**Comment by sustained** [comment]
Excellent, appreciated! :smile:

**Comment by danigb** [comment]
https://www.npmjs.com/package/@tonaljs/range
