### ISSUE TITLE
@tonaljs/midi type definitions misplaced

### ISSUE THREAD

**Issue by JackCA** [tonaljs/tonal#112]
The [@tonaljs/midi "types" key in its package.json ](https://github.com/tonaljs/tonal/blob/b077491aac0e1ea4a378a7592f710730153377b6/packages/midi/package.json#L17)points to a non-existent or misplaced type definition file.

The file exists but it's currently sitting in `dist/midi/index.d.ts` and not `dist/index.d.ts`

**Comment by danigb** [comment]
Thanks for reporting 👍

**Comment by JackCA** [comment]
@danigb thanks for the amazing library!
