### ISSUE TITLE
Degrees

### ISSUE THREAD

**Issue by martijnmichel** [tonaljs/tonal#113]
It might be nice to have degrees of a given chord and scale (key).

For instance C major would have:
Cmaj7
Dm7
Em7
Fmaj7
G7
Am7
Bm7b5

For Am melodic minor scales:
A melodic minor
B phrygian #6 
C lydian #5
D mixolydian #11
E mixolydian b13

etcetera...

I just found out about tonal so i prolly have the internal naming of the chords and scales written down differntly but could certainly see some options for this to be useful.

**Comment by danigb** [comment]
Hi,

Is https://github.com/tonaljs/tonal/tree/master/packages/scale what are you looking for?:

```js
import { scale } from '@tonaljs/scale'
scale("c5 pentatonic").notes // => ["C5", "D5", "E5", "G5", "A5"],
```

**Comment by martijnmichel** [comment]
No.. the scales are fine. Im talking about degrees within a key.

**Comment by martijnmichel** [comment]
https://en.wikipedia.org/wiki/Degree_(music)

**Comment by danigb** [comment]
Ah, ok... something like this? https://github.com/tonaljs/v2/tree/master/extensions/key

The `key` module is not in v3 (yet)

**Comment by martijnmichel** [comment]
Yes! :) great.. when does it come to v3?

**Comment by danigb** [comment]
I'll try to do it this weekend 👍

**Comment by martijnmichel** [comment]
Cool, and will they work on advanced scales like melodic minor too?

**Comment by danigb** [comment]
Not planned... as far as I know is not a "key"... but I'm open to suggestions both API and implementation. What would you like to have and behave?

**Comment by martijnmichel** [comment]
Well its not a key but comes from alterations yea.. still for jazz musicians its very nice to know what a degree of melodic minor can be and they teach you in conservatory aswell. Might aswell add it. Some weird scales come out of it ;)

Functionality should be just about the same as it would be a normal key.

Scales/chords built from the notes of a given scale:
a b c d e f# g# - melodic minor - AmMaj7
b c d e f# g# a - phrygian #6 - Bm7
c d e f# g# a b - lydian #5 - Cmaj7
and such..

Probably some of these chords and scales that come out of these already exist in tonal.

**Comment by martijnmichel** [comment]
http://tocadomusic.nl/guitarneck/
thinking of rebuilding this into a more modern one with tonal.
http://tocadomusic.nl/wp-content/customs/guitarneck/scales.json

**Comment by danigb** [comment]
Nice! 👍

**Comment by claytonmarinho** [comment]
Hi @danigb, Tonaljs is really great. Well done!
I'm currently also looking forward to getting degrees from a given chord/note and scale. Hope you can make it soon :) 
Cheers.

**Comment by martijnmichel** [comment]
Is this going to be added to v3 still ?

**Comment by danigb** [comment]
Sorry, I'm pretty busy right now. I'll implement as soon as possible. Meanwhile, you can use https://www.npmjs.com/package/tonal-key as a replacement

**Comment by danigb** [comment]
Just landed! https://github.com/tonaljs/tonal/tree/master/packages/key 

Improvements, suggestions and PRs welcomed 👍
