### ISSUE TITLE
[chord-dictionary] duplicate definition for `dominant #9`

### ISSUE THREAD

**Issue by mmmveggies** [tonaljs/tonal#116]
Is this intended? There are two definitions, both exactly the same.
- [section `'''altered'''`](https://github.com/tonaljs/tonal/blob/master/packages/chord-dictionary/data.ts#L38)
`["1P 3M 5P 7m 9A", "dominant #9", "7#9"]`
- [section `'''other'''`](https://github.com/tonaljs/tonal/blob/master/packages/chord-dictionary/data.ts#L51)
`["1P 3M 5P 7m 9A", "dominant #9", "7#9"]`

**Comment by danigb** [comment]
Fixed! Thanks 👍
