### ISSUE TITLE
roman-numeral example is not correct

### ISSUE THREAD

**Issue by ssteinerx** [tonaljs/tonal#123]
In the example, 
```
js romanNumeral("bVII7")
```
is shown to translate to a major 7 chord; it should be a dominant chord.

Above this, in the summary it says:
>  A roman numeral symbol is a string like `"bVIImaj7"`

But the example shows "bVII7" being incorrectly translated to the major 7 chord.

I think that changing the example call to:
```js
romanNumeral("bVIImaj7");
```
Would solve the issue.

**Comment by danigb** [comment]
Thanks! 👍
