### ISSUE TITLE
Wrong alias in scale-dictionary neopolitan major !== dorian b2

### ISSUE THREAD

**Issue by eagor** [tonaljs/tonal#131]
This alias is wrong, since last note of Dorian b2 is 7m, not 7M ([wiki](https://en.wikipedia.org/wiki/Dorian_%E2%99%AD2_scale))

https://github.com/tonaljs/tonal/blob/8b9f9eb2d9892e5c3f4de025e330961cea878af9/packages/scale-dictionary/data.ts#L88

Like here:
https://github.com/tonaljs/tonal/blob/8b9f9eb2d9892e5c3f4de025e330961cea878af9/packages/scale-dictionary/data.ts#L64-L69

**Comment by danigb** [comment]
Yep! Thanks!!
