### ISSUE TITLE
Problem with dim, dim7, and alt7 in Chord package

### ISSUE THREAD

**Issue by vellebelle** [tonaljs/tonal#132]
I have been using the chord dictionary to pull out the names of all chords. If I take the entries() and get all the names, many of them are empty strings. I therefore took the first item in the aliases array instead. When I pass them to the chord function it works for the most part. However, there are  problems with dim, dim7, and alt7.

chord('dim') returns an object where the empty property is true. However chord('°') and chord('o') returns what is expected - an object with lots of beautiful information :)

Same problem for chord('dim7'). But chord('°7') and chord('o7') works as expected.

chord('alt') has the same problem. And there are no alternatives since 'alt' is the only alias on the object.

**Comment by danigb** [comment]
Thanks for reporting! 👍  I'll look into it asap

**Comment by danigb** [comment]
I hope is fixed in latest published version. Please feel free to reopen if not.

**Comment by rowild** [comment]
Just tested it and it seems to work now. Thank you @danigb !!!
