### ISSUE TITLE
some sacales return notes with flat and other with sharps sign

### ISSUE THREAD

**Issue by pleshakovalexander** [tonaljs/tonal#133]
examples:
```javascript 
scale('c chromatic')
```
```json
{
  "empty": false,
  "name": "C chromatic",
  "setNum": 4095,
  "chroma": "111111111111",
  "normalized": "111111111111",
  "intervals": [
    "1P",
    "2m",
    "2M",
    "3m",
    "3M",
    "4P",
    "5d",
    "5P",
    "6m",
    "6M",
    "7m",
    "7M"
  ],
  "aliases": [],
  "type": "chromatic",
  "tonic": "C",
  "notes": [
    "C",
    "Db",
    "D",
    "Eb",
    "E",
    "F",
    "Gb",
    "G",
    "Ab",
    "A",
    "Bb",
    "B"
  ]
}
```
---
```javascript 
scale('e major')
```
```json
{
  "empty": false,
  "name": "E major",
  "setNum": 2773,
  "chroma": "101011010101",
  "normalized": "101010110101",
  "intervals": [
    "1P",
    "2M",
    "3M",
    "4P",
    "5P",
    "6M",
    "7M"
  ],
  "aliases": [
    "ionian"
  ],
  "type": "major",
  "tonic": "E",
  "notes": [
    "E",
    "F#",
    "G#",
    "A",
    "B",
    "C#",
    "D#"
  ]

```

**Comment by danigb** [comment]
This is a feature. Scales has their own spelling. For example, E major key has four sharps. It's normal that E major chord is written the same. The only exception is chromatic, that can be written in with both. 

When not using scales (for example https://github.com/tonaljs/tonal/tree/master/packages/range#rangenotes-arraystringnumber-options--string) there's an option to choose if you prefer sharps or flats.

Please reopen if I misunderstood your issue

**Comment by pleshakovalexander** [comment]
@danigb oh, I didn't notice it. Nice feature. But in my case, I get c chromatic for all notes in piano and then compare some notes in arrays, but because of different signature i can't do it. What the better way to compare notes?

**Comment by danigb** [comment]
If you don't mind the names, the easiest way is to convert them first to midi notes, and then compare. If you don't mind the order, sort the arrays before comparing.

Hope it helps

**Comment by pleshakovalexander** [comment]
@danigb oh, why i didn't think of that. You really helped me. Thank you

**Comment by pleshakovalexander** [comment]
@danigb one more question about this. How I can get the note degree if i can't compare names? Before i was getting the index in the note array that i get from the scale. So i have an array of full notes of one octave(without numbers) and of notes in the scale and i map all notes array to array of objects with note name and degree that i get from index in scale array. I hope you can understand me

**Comment by danigb** [comment]
Sorry for the delay, I've missed your message. I don't understand what are you trying to achieve. What are the scale defrees for?
