### ISSUE TITLE
"m7b5" exists twice

### ISSUE THREAD

**Issue by rowild** [tonaljs/tonal#135]
Don't know if this is on purpose, but m7b5 exists twice in the dictionary and therefore also produces 2 results, when listed.

![m7b5-twice](https://user-images.githubusercontent.com/213803/76078269-92c5d200-5fa2-11ea-99a7-871173453a1a.png)

**Comment by danigb** [comment]
Thanks for reporting 👍  Nice UI, by the way 👏

**Comment by rowild** [comment]
Thank you for fixing this so quickly!!!
