### ISSUE TITLE
Is there a "communication" channel anywhere?

### ISSUE THREAD

**Issue by rowild** [tonaljs/tonal#141]
I was wondering if there is a Slack of Gitter or Discord channel for tonaljs, where we could exchange ourselves. So far I didn't find anything like that. Did I oversee something? If not, any chance to create such a channel?

**Comment by danigb** [comment]
Open to ideas/suggestions (although, right now I can't handle more communication channels 😱 😂  )

**Comment by rowild** [comment]
Does that mean you already have some communication channel?

The main reason I ask is, because I find github not the right lace to ask question... I assume there is also no forum?

Are you mainly on Slack, Gitter or Discord? I could open a channel on any of your preferred platforms, invite you and ... well, get going... :-)

**Comment by danigb** [comment]
For me it's ok to ask questions here (at least, while they are only a few). I don't think I can watch another stream, sorry 🤷‍♀

**Comment by rowild** [comment]
Ok, understood! Thanks!
