### ISSUE TITLE
[Question] How are chords calculated?

### ISSUE THREAD

**Issue by rowild** [tonaljs/tonal#153]
Hi!

I have a little app that displays chords tonal.js produces with VexFlow:
https://codesandbox.io/s/list-of-tonaljs-chords-ntjye

Currently it has errors, because when "h11" gets displayed, the accidentals are not placed properly. But this actually happens, because VexFlow orders the pitches anew, so in the given example D4 and F4 are moved to earlier places in the array, but the accidentals keep their respective positions. So when the 2 get combined, the generated result is often times wrong.

Which brings me to my question: How does a chord like this come into existence? Why are the notes D4 and F4 at the end of the array, but still at a lower register?

Thank you!

![Bildschirmfoto 2020-03-25 um 16 46 53](https://user-images.githubusercontent.com/213803/77569793-0e90ab80-6ecb-11ea-8ba3-c08d2989dce4.png)
 the notes

**Comment by danigb** [comment]
Hi @rowild 

Yes, I think this chord is misleading and also very uncommon to say the best. So I think, the best thing to do is remove it completely from the dictionary.

Regarding your question, there's this chord type dictionary where all chords are defined: packages/chord-type/data.ts

Feel free to edit (https://github.com/tonaljs/tonal/edit/master/packages/chord-type/data.ts) and open a PR to add, remove or fix chord types.

**Comment by rowild** [comment]
Hi @danigb  
Thank you for your response!

 So if I understand you correctly that means that initially all chords are added manually via the `data.ts`, right?
The mentioned chord "h11" seems to be the only one where the "order" is "not in order" (lower notes succeed higher notes). And I assume this just happened when it was added manually to the dictionary - right?

How about fixing the order of the chord in question instead of deleting it? 
C4 - Eb4 - Gb4 - Bb4 - D5 - F5

**Comment by danigb** [comment]
Hi @rowild 

I've checked the data and I've just taken two actions (before reading your message, sorry):
- I've re-ordered one of the chords (like you proposed)
- I've removed the other one. The reason: I'm not sure that an structure with C, D, E and F (four consecutive notes) can be called a chord. Even with the most relaxed term this structure doesn't produce any "harmony". So I've decided to delete.

Anyway, I'm open to suggestions... but I'd like to find at least a documentation that references this chord.

What do you think?

**Comment by rowild** [comment]
What do you mean by "one of the chords"? (If you refer to the `m1b5` and `h11` I have to admit that I was of the opinion that these are two namings for the same chord structure.)

As for the 2nd point: I do agree, but is this a problem concerning this/these chord(s)? When replacing to a higher register, there will not be any scale fragments anymore, but a clean structure of thirds...)

Background: I am mainly trained in contemporary classic (set theory, spectral, etc), using chords (as an e.g. jazz musician does) was never a big topic for me. So I might get the whole naming of the chords wrong (or at least in this case...). This is also the reason, why I prefer to confer with you first before suggesting any changes via PR. Hope that's ok with you! Gracias!

**Comment by honkskillet** [comment]
What is an h11 chord?  I'm not familiar with the H naming conventions.  How does that work?
I found it here https://www.solfej.io/chords/a-sharp-h11

**Comment by honkskillet** [comment]
Oh.  It's just a B chord?
