### ISSUE TITLE
b9sus & phryg produce different results

### ISSUE THREAD

**Issue by rowild** [tonaljs/tonal#154]
Test app:
https://codesandbox.io/s/list-of-tonaljs-chords-ntjye

the 2 mentioned chords, set 3154, should be 2 namings for the same chord. But they create 2 different results. is that on purpose?

**Comment by danigb** [comment]
Hi,

First thing first: you app it's starting to look awesome! Congrats 👏 

Looking at the chord data (chord-type/data.ts) I can see both names are aliases, so they should produce same results.
In fact, at my console both produces the exact same output (as expected):
```js
Chord.get('C phryg'); // =>
{
  empty: false,
  name: 'C suspended 4th b9',
  setNum: 3154,
  chroma: '110001010010',
  normalized: '100010100101',
  intervals: [ '1P', '4P', '5P', '7m', '9m' ],
  quality: 'Unknown',
  aliases: [ 'b9sus', 'phryg' ],
  type: 'suspended 4th b9',
  tonic: 'C',
  notes: [ 'C', 'F', 'G', 'Bb', 'Db' ]
}
```

and:

```js
Chord.get('C b9sus'); // =>
{
  empty: false,
  name: 'C suspended 4th b9',
  setNum: 3154,
  chroma: '110001010010',
  normalized: '100010100101',
  intervals: [ '1P', '4P', '5P', '7m', '9m' ],
  quality: 'Unknown',
  aliases: [ 'b9sus', 'phryg' ],
  type: 'suspended 4th b9',
  tonic: 'C',
  notes: [ 'C', 'F', 'G', 'Bb', 'Db' ]
}
```

How are you generating that notes?

Regarding you question: yes, it can be some different chords with same chroma. But they are rare, and not this case.

**Comment by rowild** [comment]
Hi, @danigb !
Thank you for your motivating feedback! :-)

I found my mistake: I didn't send a root key to Chords.get(), but only the string of the chord type:
```javascript
// wrong
Chords.get('b9sus') ...

// correct
Chords.get('C b9sus') ...

```

That's why the b got cut off and was consequently interpreted as a completely different chord.

Thanks a ton for posting your examples!!! Highly appreciated!
