### ISSUE TITLE
Chords detection bug still for even the update version

### ISSUE THREAD

**Issue by MJKEYS21** [tonaljs/tonal#157]
Getting some messed up chord names first when a play a chord but when played and then hitting the root and second time it shows the right chords if you can tell me which to edit that would be good cause i have studied music theory so i know all the music basics

**Comment by rowild** [comment]
Without code it is hard to help. Can you share the relevant pieces of your scripts?

**Comment by MJKEYS21** [comment]
which ones there are a lot of them

**Comment by MJKEYS21** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/62490852/79051830-04bfb580-7bf8-11ea-86ae-aee0986221cc.png)

**Comment by MJKEYS21** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/62490852/79051851-15702b80-7bf8-11ea-9103-93c6aa698050.png)

**Comment by MJKEYS21** [comment]
i just realized im using the old version

**Comment by MJKEYS21** [comment]
how do i update it without going through everything again

**Comment by rowild** [comment]
You should post YOUR code, note images of your folder.
to update to the latest version use `npm i @tonajs/tonal` as it says in the readme.

**Comment by MJKEYS21** [comment]
ohk

**Comment by MJKEYS21** [comment]
im using git bash is that ohk to use

**Comment by MJKEYS21** [comment]
i got this error

daw24@LAPTOP-86CFVB0D MINGW64 ~/Downloads/Chord Detect
$ npm i @tonajs/tonal
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tonajs%2ftonal - Not found
npm ERR! 404
npm ERR! 404  '@tonajs/tonal@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\daw24\AppData\Roaming\npm-cache\_logs\2020-04-11T19_30_49_287Z-debug.log

**Comment by vapurrmaid** [comment]
You clearly have a typo "@tonajs"

**Comment by MJKEYS21** [comment]
Ohk thanks

**Comment by MJKEYS21** [comment]
copy and paste error

**Comment by MJKEYS21** [comment]
i updated it but the chords are still wrong

**Comment by rowild** [comment]
How do you generate the chord? You need to post your code!

**Comment by vapurrmaid** [comment]
> You should post YOUR code, note images of your folder.
> to update to the latest version use `npm i @tonajs/tonal` as it says in the readme.

^ typo is here too, it happens.

Should be

```bash
npm i @tonaljs/tonal
```

**Comment by MJKEYS21** [comment]
> How do you generate the chord? You need to post your code!

![Screenshot (6)](https://user-images.githubusercontent.com/62490852/79053281-c5966200-7c01-11ea-8600-765c6b7a8272.png)

**Comment by MJKEYS21** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/62490852/79053294-e1016d00-7c01-11ea-9fb8-47bb739dd05b.png)

**Comment by danigb** [comment]
Hi,

You're still using the old version. You need:
```
const tonal = require('@tonaljs/tonal);
tonal.ChordDetect.detect(["Bb", "D", "F#"]);
```

Hope it helps. Thanks everyone for the responses!! ❤️

**Comment by MJKEYS21** [comment]
> Hi,
> 
> You're still using the old version. You need:
> 
> ```
> const tonal = require('@tonaljs/tonal);
> tonal.ChordDetect.detect(["Bb", "D", "F#"]);
> ```
> 
> Hope it helps. Thanks everyone for the responses!! ❤️

so should i delete and or replace a line ?

**Comment by rowild** [comment]
Add
```
const tonal = require('@tonaljs/tonal);
```
on the very top of your script.

And replace your 

```
const Chords = Detect.chord(namedNotes)
```

With

```
// Kep the old code
// const Chords = Detect.chord(namedNotes)
const Chords = tonal.ChordDetect.detect(namedNotes);
```

I assume at least. I don't have a MaxMSP at hand...

**Comment by MJKEYS21** [comment]
ohk thanks for the help

**Comment by MJKEYS21** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/62490852/79053508-908b0f00-7c03-11ea-8ef8-204e13ca22d7.png)

**Comment by rowild** [comment]
It would be a lot easier to help if you could copy and paste the code instead of adding an image...

**Comment by MJKEYS21** [comment]
ohk

**Comment by MJKEYS21** [comment]
const tonal = require("@tonaljs/tonal");
const maxApi = require("max-api");
const Detect =require("tonal-detect"); 

maxApi.outlet("yrreeree");

maxApi.addHandler("detect" , (...midiNotes) => {
 const namedNotes = midiNotes.map(tonal.Note.fromMidi);
 //const chords = Detect.chord(namedNotes);
 tonal.ChordDetect.detect(["Bb", "D", "F#"]);
 const Chords = tonal.ChordDetect.detect(namedNotes);
 if (chords && chords.length > 0) {
     maxApi.outlet("chords", ...chords);
     } else {
        maxApi.outlet("chords", "No Chord");
     }
   
});

**Comment by rowild** [comment]
OK, almost... now please edit your last post and put 3 back ticks before the first and last line of your code example as described here (and add "javascript")

**Comment by MJKEYS21** [comment]
im not sure i understand what you mean could you elaborate more please

**Comment by rowild** [comment]
It is about formatting text to make it better readable. Please make yourself familiar with markdown on github - it helps a lot!

Anyway, try this:

```javascript
const tonal = require("@tonaljs/tonal");
const maxApi = require("max-api");

maxApi.outlet("yrreeree");

maxApi.addHandler("detect" , (...midiNotes) => {
  const namedNotes = midiNotes.map(tonal.Note.fromMidi);
  const Chords = tonal.ChordDetect.detect(namedNotes);
  if (chords && chords.length > 0) {
    maxApi.outlet("chords", ...chords);
  } else {
    maxApi.outlet("chords", "No Chord");
  }
});
```

**Comment by rowild** [comment]
EDIT:
only `Chord.detect` not `ChordDetect.detect` on line 8
and on line 9 "Chords" is capitalized, but not used as such in the `if`  statement; so make it lowercase...
(fixed previous code sample)

**Comment by MJKEYS21** [comment]
ohk

**Comment by MJKEYS21** [comment]
but im still getting some messed up chord names

**Comment by MJKEYS21** [comment]
like fmaj7 is showing Amaj7

**Comment by rowild** [comment]
Please do the following (but I don't know if that woks within MaxMSP):

```javascript
const tonal = require("@tonaljs/tonal");
const maxApi = require("max-api");

maxApi.outlet("yrreeree");

maxApi.addHandler("detect" , (...midiNotes) => {

  console.log("midiNotes =", midiNotes)

  const namedNotes = midiNotes.map(tonal.Note.fromMidi);

  console.log("namedNotes =", namedNotes)

  // Also, you want ONE chord that consists of MANY notes, right? I would recommend to
  // rename "chords" to "chord"
  const chord = tonal.Chord.detect(namedNotes);

  console.log("chord =", chord)

  if (chord && chord.length > 0) {
    // The outlet still is called "chords" (that is a MaxMSP thingy here, right? 
    // Or not? If not, change to singular)
    maxApi.outlet("chords", ...chord);
  } else {
    maxApi.outlet("chords", "No Chord");
  }
});
```

And then let us know what the console outputs do... (now a screenshot would be helpful :-) ...)

**Comment by MJKEYS21** [comment]
i dont think this is max msp

**Comment by MJKEYS21** [comment]
lol ohk

**Comment by rowild** [comment]
Oha --- what is it then?

**Comment by MJKEYS21** [comment]
max 8

**Comment by MJKEYS21** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/62490852/79054248-11003e80-7c09-11ea-9213-55cf869e0519.png)

its still saying some messed up chords

**Comment by MJKEYS21** [comment]
i mean i studied music theory if there was a way i could help just let me know

**Comment by MJKEYS21** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/62490852/79054292-53c21680-7c09-11ea-9376-8498b8145768.png)

**Comment by rowild** [comment]
In the "if" clause change "chords" to "chord".

It seems you don't get a console output... hmmm... 

...and Max 8 is what is known (or was known before Ableton bought it?) as MaxMSP :-)

**Comment by MJKEYS21** [comment]
ok

**Comment by MJKEYS21** [comment]
yea if i singular "chords" to "chord" debug gives me errors

**Comment by rowild** [comment]
Post them

**Comment by MJKEYS21** [comment]
i fixed it already

**Comment by MJKEYS21** [comment]
const tonal = require("@tonaljs/tonal");
const maxApi = require("max-api");

maxApi.outlet("yrreeree");

maxApi.addHandler("detect" , (...midiNotes) => {

  const namedNotes = midiNotes.map(tonal.Note.fromMidi);

  console.log("namedNotes =", namedNotes)
  
  const chord = tonal.chord.detect(namedNotes);

  console.log("chords =", chords)
  
  if (chords && chords.length > 0) {
    maxApi.outlet("chords", ...chords);
  } else {
    maxApi.outlet("chords", "No Chord");
  }
});

**Comment by rowild** [comment]
PLease format your code!

**Comment by rowild** [comment]
you need to pu 3 back ticks before and after the code, like this:

` ` ` javscript
[the code]
` ` `

but WITHOUT the empty spaces between the ticks from my example!

And still no "console.logs"?

**Comment by MJKEYS21** [comment]
ohk im doing that now

**Comment by rowild** [comment]
And it seems you didn't fix the plural "chords" to singular "chord" in the if clause. 
And here, in "tonal.Chord.detect", the "Chord" part MUST be capitalized! That is a tonaljs Object, not you variable.

Anyway: Since you only need Note and Chord from the library, let's try importing only those:

```javascript
const { Note, Tonal } = require("@tonaljs/tonal");
const maxApi = require("max-api");
maxApi.outlet("yrreeree");

maxApi.addHandler("detect" , (...midiNotes) => {
  const namedNotes = midiNotes.map(Note.fromMidi);

  // to avoid confusion, let's rename this variable
  const newChord = Chord.detect(namedNotes);

  if (newChord && newChord.length > 0) {
    // maybe "chords" must be renamed to "newChord", too... but I do not know
    // what this string really does, so you must try...
    maxApi.outlet("chords", ...newChord);
  } else {
    maxApi.outlet("chords", "No Chord");
  }
});
```

**Comment by MJKEYS21** [comment]
the debug says chord is not defined

**Comment by MJKEYS21** [comment]
is there a way to just re install is from scratch so its better done

**Comment by MJKEYS21** [comment]
because the original coding that made it work  is being messed up when i try to add new codes so im wondering if can just get a set by step procedure to uninstalling and installing over tonal

**Comment by rowild** [comment]
The API of tonal changed, so if you use the new version, you need to change your code. Or you revert to an old version of tonal and use your old script.

**Comment by MJKEYS21** [comment]
i dont think i get what your saying

**Comment by MJKEYS21** [comment]
cant i just remove the files and then start a new javascript file in vs code then install tonal (new version) and then input the codes?

**Comment by rowild** [comment]
I tested your code locally and the javascript parts work. Here is a screenshot:

![Screen Shot 2020-04-11 at 23 29 15](https://user-images.githubusercontent.com/213803/79055308-6578dd80-7c4c-11ea-8c8c-4bbfc48c0aed.png)

So either there is a typo anywhere or the Javascript that Max provides, works differently.

**Comment by MJKEYS21** [comment]
oh Ohk

**Comment by MJKEYS21** [comment]
well i created a new javascript and copied my profile so im gonna try again to see what happens could you stay by to ensure its done properly please

**Comment by rowild** [comment]
It is a bit late here in Vienna, Austria. I am about to go to sleep. I will look into it tomorrow again.

(If you want you can also hit me per email and we arrange a skype session.)

Finally a second screenshot with what you get, when a Cmin7 chord is entered:

![Screen Shot 2020-04-11 at 23 32 31](https://user-images.githubusercontent.com/213803/79055442-652d1200-7c4d-11ea-9bea-c069a2a7c138.png)

**Comment by MJKEYS21** [comment]
Oh ok wow

**Comment by MJKEYS21** [comment]
thanks man

**Comment by MJKEYS21** [comment]
heres my email martelmartin8@gmail.com

**Comment by MJKEYS21** [comment]
> tonal.ChordDetect.detect(["Bb", "D", "F#"]);

aye i tried starting over by installing over the file
