### ISSUE TITLE
[Question/"Feature request"] Provide lib on a CDN?

### ISSUE THREAD

**Issue by rowild** [tonaljs/tonal#159]
Hi, @danigb !

I was just wondering how to implement tonaljs on jsfiddle or codepen. I assume a library release on a CDN would be necessary right? If so, any chance to provide one?

Thank you!

**Comment by danigb** [comment]
Hi @rowild 

Yes, here it is: https://github.com/tonaljs/tonal/blob/master/packages/tonal/browser/tonal.min.js
Although I don't know how to put it into a CDN... ideas o PR welcomed 👍

**Comment by rowild** [comment]
Ah, excellent! Thank you!
As for CDN, I'll check that out.

**Comment by rowild** [comment]
It seems jsDelivr is a fantastic solution since there is not need to load anything up anywhere. It just reads from the github repo. See this article:
https://gomakethings.com/how-to-turn-any-github-repo-into-a-cdn/

But in order to do so, the tonal.min.js needs to reside in a "visible" folder ("blob" isn't visible). So if you could find a way to automate a "dist" (or "release" or sth similar) folder that holds an automatically generated "tonal.min.js", then the CDN link would be:

https://cdn.jsdelivr.net/tonaljs/tonal/dist/tonal.min.js

And you could simply post it in your readme...

**Comment by danigb** [comment]
Thanks for the links! Working towards get it available (easily) with jsdelivr
