### ISSUE TITLE
slash chords are not correct they are showing different bass notes not based onthe  bass note but what note you touch after  

### ISSUE THREAD

**Issue by MJKEYS21** [tonaljs/tonal#164]
meaning you hold E/C and if you continue holding it touch a G the bass note changes to G/C

**Comment by danigb** [comment]
True. Bass chords are not supported. Working on this

**Comment by MJKEYS21** [comment]
Thank you I have mr Robert working as well but u should continue to help in
case his method doesn't work

**Comment by MJKEYS21** [comment]
Ohk so help me with this  i want to show the scale type when held

**Comment by MJKEYS21** [comment]
its not that i cant do it but your the expert here i=and i have tried some
method but i dont wanna screw up my work

**Comment by MJKEYS21** [comment]
ohk so in all
help me to use the notes folder
the transpose option
and scales
