### ISSUE TITLE
how to do you make the other chord names smaller?

### ISSUE THREAD

**Issue by MJKEYS21** [tonaljs/tonal#166]

**Comment by danigb** [comment]
I don't understand what you mean. Can you elaborate, please?

**Comment by MJKEYS21** [comment]
Srry about that I was saying if you could adjust JavaScript font size
because in music theory you have the root chord and other chords it could
be so I'm saying if the other chords can be smaller

**Comment by danigb** [comment]
Not Tonal related. You can change font size using the browser (or css).

**Comment by MJKEYS21** [comment]
Ohk thanks

**Comment by MJKEYS21** [comment]
I probably should have asked a different question more related
