### ISSUE TITLE
[Question] naming of scale seems strange...

### ISSUE THREAD

**Issue by rowild** [tonaljs/tonal#170]
In `scle-type`, line 54, the `aeolian` naming convention is different fromt the others (within single quotes, but aeolian itself is preceded by double quotes: 
```
["1P 2M 3m 4P 5d 6m 7m", "locrian #2", "half-diminished", '"aeolian b5'],
``` 
Is that on purpose? If so, what is the reason for this naming convention?
Thank you!

**Comment by danigb** [comment]
I think that's a typo! 😱 Good catch! PR welcomed!

**Comment by rowild** [comment]
Coming in a moment...

**Comment by rowild** [comment]
PR merged. Hostia, que rrrrrapido!!
