### ISSUE TITLE
Could not find a declaration file for module '@tonaljs/tonal'

### ISSUE THREAD

**Issue by samuelrafini** [tonaljs/tonal#174]
When I import tonal for example ``` import { Note } from "@tonaljs/tonal";``` in my ts file I get the warning/error ```Could not find a declaration file for module '@tonaljs/tonal'```

**Comment by samuelrafini** [comment]
I found another way but I don't know if it's the correct way ``` import Note from "@tonaljs/note/dist";
```

**Comment by mrjacobbloom** [comment]
I'm getting this too. It looks like the declarations file for the `@tonaljs/tonal` package is generated at `dist/index.d.ts`, but the package.json has `"types": "dist/index.dt.ts"`
