### ISSUE TITLE
TypeError: Note is undefined

### ISSUE THREAD

**Issue by oxk4r01** [tonaljs/tonal#176]
I'm triying to start using tonal.js in VisualStudioCode with Nodejs and Parcel.js as bundler. 
Here is my file structure and the package.json:
![image](https://user-images.githubusercontent.com/1032224/81160858-eba5ec80-8f8a-11ea-8148-ef5c37e56669.png)

But with a simple console.log() for testing, I'm getting this error:
![image](https://user-images.githubusercontent.com/1032224/81161195-7be43180-8f8b-11ea-8143-0c42be853cce.png)

**Comment by danigb** [comment]
Sorry! Update library to 3.7.4 and should be working again. Thanks for reporting

**Comment by oxk4r01** [comment]
It seems solved. Thank you and regards :)
