### ISSUE TITLE
Getting all chords of exotic and minor modal scales

### ISSUE THREAD

**Issue by cambo2015** [tonaljs/tonal#177]
Thank you for this library! I am trying to get all the chords for Dorian b2 scale. I followed the documentation and used the chords(); I was able to get the chords for major and its modes, but I couldn't get anything for Dorian b2. Thanks!

**Comment by danigb** [comment]
It works for me (scale names are lowercase):
```js
Scale.scaleChords('dorian b2')
[
  '5',       'sus4',
  '7sus4',   'm',
  'm7',      'm6',
  '4',       'madd4',
  'm7add11', 'b9sus',
  '11b9'
]
```

Please reopen if not working for you (and some code snippets will be appreciated)

**Comment by cambo2015** [comment]
Thanks I got it to work! the Scales.scaleChords didn't work but Scale.chords() did. Thanks :+1:
