### ISSUE TITLE
Function for note equality that ignores accidentals

### ISSUE THREAD

**Issue by thebne** [tonaljs/tonal#178]
I wanna compare two pitch classes and see if they are represented by the same key in the piano.
So basically:

```js
> Note.same('C#', 'Db')
true
```

Right now I can do that if I cast it to midi (`Midi.toMidi(a) === Midi.toMidi(b)`) but it doesn't work on pitch classes, only on notes with scales.

Edit:

Ideally, I would also want a way to know a deterministic name for each of those, so I could use them as keys for objects etc. 
Right now I'm using ```Note.pitchClass(Midi.midiToNoteName(Midi.toMidi(`${note}1`)))```...

**Comment by danigb** [comment]
There's the `height` value: it's like midi but works for pitch classes:

```js
Note.get('C#').height === Note.get('Bb').height
```

Hope it works. Please reopen if not solved.

**Comment by thebne** [comment]
@danigb ah, I missed that. Can I also go backwards though?
Can I get a (any) representation of the height as a pitch class? Unless I'm missing something again, it looks like it'll only work with a reverse hash map or so (`{height: note}`), which brings me to square one
