### ISSUE TITLE
Chord +maj7 on grade 3 in melodic minor not found in chordType.all

### ISSUE THREAD

**Issue by martijnmichel** [tonaljs/tonal#179]
as stated in topic when converting the named chord from tonal.key melodic minor grade III the chord is not found, probably due to faulty naming.

```
melodic: {
    tonic: "C",
    grades: ["I", "II", "bIII", "IV", "V", "VI", "VII"],
    intervals: ["1P", "2M", "3m", "4P", "5P", "6M", "7M"],
    scale: ["C", "D", "Eb", "F", "G", "A", "B"],
    chords: ["Cm6", "Dm7", "Eb+maj7", "F7", "G7", "Am7b5", "Bm7b5"],
    chordsHarmonicFunction: ["T", "SD", "T", "SD", "D", "-", "-"],
    chordScales: ["C melodic minor", "D Dorian b2", "Eb Lydian augmented", "F Lydian dominant", "G Mixolydian b6", "A locrian 9", "B altered",
    ],
  },
```

**Comment by martijnmichel** [comment]
Also, isn't the first chord CmMaj7 instead of Cm6? ;/

**Comment by martijnmichel** [comment]
it must either be renamed inside tonal.key or added as alias in tonal.core

if found this in chordType lib
["1P 3M 5A 7M", "augmented seventh", "maj7#5 maj7+5"],

**Comment by martijnmichel** [comment]
I've solved it by adding it with Chord.add() though maybe you're right for reopening it.

**Comment by danigb** [comment]
Thanks for reporting! 👍  

You're right, the actual chord is `CmMaj7` but `Cm6` represents better it's function 🤔  I think I'd probably change to `CmMaj7` (for consistency), although I'd like to find a reference where it states that should be that one...
