### ISSUE TITLE
Error loading tonal.min.js with Microsoft Edge 18.18363

### ISSUE THREAD

**Issue by jlbocquet** [tonaljs/tonal#188]
My page is loading tonal.min.js as follows :
<script src="https://cdn.jsdelivr.net/npm/@tonaljs/tonal/browser/tonal.min.js"></script>

this error occurs:

![error](https://user-images.githubusercontent.com/42833448/82232600-2286e580-992f-11ea-9e7d-b510324bd247.png)

**Comment by danigb** [comment]
Hi,

I'd need more information about the error. I've just tested in the browser I have available and it works... 🤔
