### ISSUE TITLE
height doesn't handle edge case (Cb!=B)

### ISSUE THREAD

**Issue by thebne** [tonaljs/tonal#189]
see #178 (my last comment).

it looks like it works with a valid example:

```js
> Note.get('D#').height 
-1185
> Note.get('Eb').height
-1185
```

But notice what happens on the "edges" of your scale:
```js
> Note.get('Cb').height
-1189
> Note.get('B').height
-1177
// this solves it
> Note.get('Cb-99').height
-1177
```

**Comment by MJKEYS21** [comment]
doesnt look anybody is gonna answer......cause i have been emailing this guy from the last 2 months and he has not answered so this is pointless tbh

**Comment by danigb** [comment]
@thebne Yes, your're right! Working on a fix 👍
