### ISSUE TITLE
Frequency to note?

### ISSUE THREAD

**Issue by MysteryPancake** [tonaljs/tonal#190]
I apologize for opening an issue on this, but I am wondering if this library contains functionality to convert from a frequency to a note? I am currently using this code from [pitchdetect.js](https://github.com/cwilso/PitchDetect/blob/master/js/pitchdetect.js#L207-L212):
```
const noteStrings = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];

function noteFromPitch(frequency) {
	return noteStrings[(Math.round(12 * (Math.log(frequency / 440) / Math.log(2))) + 69) % 12];
}

noteFromPitch(440) -> "A"
```
I am wondering if there is any equivalent function in this library.

The closest thing I can find is:
```
Tonal.Midi.midiToNoteName(Tonal.Midi.freqToMidi(440)) -> "A4"
```
I was just wondering if there was a more direct method.

I saw that Note.fromFreq was removed, and I was wondering why this was.

**Comment by danigb** [comment]
You're right! Working on it 👍

**Comment by MysteryPancake** [comment]
Wow, that was incredibly fast, thank you!
