### ISSUE TITLE
Slash chords with the bass

### ISSUE THREAD

**Issue by dok** [tonaljs/tonal#192]
Hey @danigb, I was wondering if you'd like help implementing this. Is there a particular structure that you are thinking about when a user passes in something like:

```js
const Chord = require("@tonaljs/chord");

Chord.get('G/C')

/**
{ empty: false,
  name: 'G major',
  setNum: 2192,
  chroma: '100010010000',
  normalized: '100001000100',
  intervals: [ '1P', '3M', '5P' ],
  quality: 'Major',
  aliases: [ 'M', '' ],
  symbol: 'G',
  type: 'major',
  root: '',
  rootDegree: 0,
  tonic: 'G',
  notes: [ 'G', 'B', 'D' ] }
**/
```

What would be the ideal scenario here? How about something like:

```js
{ empty: false,
  name: 'G major',
  setNum: 2192,
  chroma: '100010010000',
  normalized: '100001000100',
  intervals: [ '4P', '1P', '3M', '5P' ],
  quality: 'Major',
  aliases: [ 'M', '' ],
  symbol: 'G',
  type: 'major',
  root: 'C',
  rootDegree: 0,
  tonic: 'G',
  notes: ['C', 'G', 'B', 'D' ] }
```

Other references: https://github.com/tonaljs/tonal/issues/164

**Comment by danigb** [comment]
Hi @dok , yes! That would be awesome.

Sou you are thinking about adding a couple of fields, right? 👇  
- `root` (string, "" by default) 
- `rootDegree` (number 0 by default, means same as tonic)

I'm wondering if "bass" instead of "root" is a better word? Looks like wikipedia uses that term: https://en.wikipedia.org/wiki/Slash_chord

Things to consider:
- What happens if the root/bass is not part of the chord? (Without going deep, I think it should return an _empty not valid_ chord)
- What happens if the root/bass is not a note?

**Comment by dok** [comment]
Adding "bass" in conjunction with the "root" property sounds good! It would be better than manipulating the root, since we won't lose information about the chord. In that case, I don't think the `rootDegree` would change either. 

> What happens if the root/bass is not part of the chord? (Without going deep, I think it should return an empty not valid chord)

I think that sounds good for now

> What happens if the root/bass is not a note?

That would be like if someone specified a "Eb/Eb" 😂. I think we can either treat it as an "Eb" or return a non-valid chord. What do you think?

**Comment by stevage** [comment]
Chiming in here. No idea if this will get implemented, but my thoughts:

- add a `bass` attribute that for `C` would be `C` and for `C/Bb` would be `Bb`.
- `name` should reflect the slash, maybe `C major over Bb`
- `aliases` should contain the slash

Harder questions:

- for `type`, should every type/slash combo be considered unique (ie, is the type of C/Bb "major over flat seventh" or is it just "major slash")
- does `intervals` include the bass note? I guess it does, but for some applications that may not be expected.

(I didn't really understand the "Without going deep, I think it should return an empty not valid chord" comment).
