### ISSUE TITLE
Is there anything for Circle of FOuths/Fifths?

### ISSUE THREAD

**Issue by SteveALee** [tonaljs/tonal#200]
First - this is such an excellent library. Thank you!

I was looking for something, possibly a 'scale', of the Circle of Fourth/Fifths. this is a pretty foundational concept.  

I realise I could generate by iterating forths or fifths but that's a  bit of run-time overkill IMHO. For now I [just use a static array](https://github.com/music-practice-tools/music-practice-tools/blob/f567818aaa11fac27a9e73fbf0b2cd8ac87833b7/src/js/widgets/random.js#L59-L73).

That's totally trivial so not any sort of problem. But I just wonder if the CoF is something missing from the library?

**Comment by danigb** [comment]
Not very nice, but possible:

```js
const fifths = [-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12]
fifths.map(num => Note.transposeFifths('C', num)) // =>
[
  'Dbb', 'Abb', 'Ebb', 'Bbb', 'Fb',
  'Cb',  'Gb',  'Db',  'Ab',  'Eb',
  'Bb',  'F',   'C',   'G',   'D',
  'A',   'E',   'B',   'F#',  'C#',
  'G#',  'D#',  'A#',  'E#',  'B#'
]
```

**Comment by sugizo** [comment]
could you explain the correlation between circle of fifths with music scales (pentatonic, hexatonic, octatonic, etc) ?

as far i know, it just show the chord and it's relative, key signatures

ref
https://en.wikipedia.org/wiki/Circle_of_fifths

**Comment by SteveALee** [comment]
@sugizo 

In retrospect I was mixing up my application that included the Circle of Fourths (CoF) and scales. 

While both define a set and sequence of ascending or descending notes, the CoF extends past the octave so I guess is significantly different to a normal scale. Identifying key signatures is one use of the CoF but is based pitch mathematics and has [other uses as well](https://www.musical-u.com/wp-content/uploads/2018/07/The-Ultimate-Guide-to-the-Circle-of-Fifths.pdf).

My use case is to pick a starting note, either from a scale or from the CoF. in the end I just [coded it explicitly](https://github.com/music-practice-tools/music-practice-tools/blob/master/src/js/widgets/random.js#L61-L83)
