### ISSUE TITLE
Chord Detect does not detect augmented chords

### ISSUE THREAD

**Issue by kalkoen** [tonaljs/tonal#204]
Consider the following code:
`let chord = Chord.get("Caug");
let testIdentify = Chord.detect(chord.notes);
console.log(testIdentify)`
Output: [ "CMb6", "EMb6/C", "G#Mb6/C" ]

Is it to be expected that Chord Detect does not indentify augmented chords? If so, why not?

**Comment by danigb** [comment]
Good point! Looks like a bug. 🤔  I'm going to look into it

**Comment by danigb** [comment]
Fixed! https://github.com/tonaljs/tonal/pull/209/files#diff-4ba7f2e276c4adf1baf19fb415e697d4R11

Thanks for reporting! 🙏
