### ISSUE TITLE
Cannot find the changelog

### ISSUE THREAD

**Issue by SteveALee** [tonaljs/tonal#212]
Hi I was using tonalsjs/tonmal 4.02 and see the latest is now 4.2.1. However, I cannot see what has changed other than looking at all the commits.

Is there a change log I missed someplace? I looked for a file in the code root and also package folders, plus the issues section of GitHub .

thanks

**Comment by danigb** [comment]
Hi Steve,

I'm afraid currently there's no changelog. I have to admit that I'm doing a poor job when communicating code changes. The only option is to see commits (fortunately each version is marked as a new commit).

Keep this issue open to remind adding one. PRs welcomed.

**Comment by SteveALee** [comment]
OK, at least I'm not missing somehting :) I'll have a rummage. I saw a couple of new modules.
