### ISSUE TITLE
Scale over given range using new API.

### ISSUE THREAD

**Issue by spidercatnat** [tonaljs/tonal#219]
It used to be the case that if I wanted a scale to span from C2 to C4, I could achieve that with the Range, Dictionary, and Transpose utilities. 

For example, in C Major:

`Range.scale(Dictionary.scale('major').map(transpose('C2')), ['C2', 'C4']);`

would yield, if I recall correctly, a scale with notes:

`[
  'C2', 'D2', 'E2', 'F2',
  'G2', 'A2', 'B2', 'C3',
  'D3', 'E3', 'F3', 'G3',
  'A3', 'B3', 'C4'
]`

I cannot figure out how to do this with the latest version. Any help is greatly appreciated. Thanks!

**Comment by danigb** [comment]
You're right! I've lost it 🙀  Working on it

**Comment by danigb** [comment]
[Here it is](https://github.com/tonaljs/tonal/tree/master/packages/scale#scalerangeofscalename-string--from-string-to-string--string) Hope it helps
