### ISSUE TITLE
Support for slash chords?

### ISSUE THREAD

**Issue by LuisRodriguezLD** [tonaljs/tonal#22]
Hello.

Great repo, is there any support for slash chords? https://en.wikipedia.org/wiki/Slash_chord
I couldn't find anything in the docs.

Like, `D/F#` ?
I'd like to transpose it but I get something like `["E", null, "G#"]`

**Comment by danigb** [comment]
Sorry, I've missed this issue. There's no support, but I'm open to ideas about how to implement it. What are the expected inputs and outputs, for example?

**Comment by derBingle** [comment]
_(**WARNING:** I'm just getting started with `tonal`, and with studying music theory in general, so there's probably a better way of doing this.)_

I'm working on a tool to convert chord charts to/from the Nashville number system, so I needed this as well. Here's my solution from 2:30 am this morning: 😆 

```javascript
const convertSlashChord = (chord, key) => {
        const getkeyInterval = Distance.interval(key);
        let splitChord = chord.split('/')

        let rootChordTokens = Chord.tokenize(splitChord[0])
        let rootChordNumber = Interval.num(fromE(rootChordTokens[0]))
        let inversionNumber = Interval.num(fromE(splitChord[1]))
        return`${rootChordNumber}${rootChordTokens[1]}/${inversionNumber}`
    }

    console.log(convertSlashChord('D/F#', 'G')) // ==> 5=7
```

**Comment by danigb** [comment]
Hi @derBingle,

As far as I know, a D/F# chord means a D major chord with F# in the bass, so I think Tonal should behave something like this:

`Tonal.Chord.notes("D/F#") // => ["F#", "A", "C"]`

If the note after the slash doesn't belong to the chord, just add it:

`Tonal.Chord.Notes("D/B") // => ["B", "D", "F#", "A"]`

Am I missing something?

I don't know understand what are you convert the slash chord into. And I don't know what the Nasville number system is, but I'm willing to learn about ;-)

**Comment by derBingle** [comment]
@danigb That's why I started with the warning at the beginning of my comment — it was written from my phone in a sleep-deprived state. 😉 Maybe I can do better this time. 

The [Nashville number system](https://en.wikipedia.org/wiki/Nashville_number_system) (NNS) is a way of writing chord charts by scale degree — very similar to the roman numeral style, but using Arabic numerals, optionally using a dash or lowercase 'm' to indicate minor chord, and with some additional symbols to represent rhythm. 

The bass notes of slash chords are represented the same way as the rest of the chords. Here's an example that will hopefully make it clearer what I was trying to accomplish. The flow is original original key => nashville => new key.

### Code
```javascript
const originalChords = ['D/F#', 'G', 'D/F#', 'G/B', 'D/A', 'D/F#', 'G', 'D/F#', 'Em7', 'A', 'D']
const nashville = originalChords.map(chord => toNashville(chord, 'D'))
const keyOfG = nashville.map(chord => fromNashville(chord, 'G'))


console.log(`Original  =>   ${originalChords.join(",  ")}`)
console.log(`Nashville =>   ${nashville.join(",  ")}`)
console.log(`Key of G  =>   ${keyOfG.join(",  ")}`)

```
### Output
```
Original  =>   D/F#,  G,  D/F#,  G/B,  D/A,  D/F#,  G,  D/F#,  Em7,  A,  D
Nashville =>   1/3,  4,  1/3,  4/6,  1/5,  1/3,  4,  1/3,  2m7,  5,  1
Key of G  =>   G/B,  C,  G/B,  C/E,  G/D,  G/B,  C,  G/B,  Am7,  D,  G
```

Thanks so much for all the work you've put in to this, @danigb. It really shows, and I, for one, really appreciate it!

**Comment by gabergg** [comment]
> @danigb That's why I started with the warning at the beginning of my comment — it was written from my phone in a sleep-deprived state. 😉 Maybe I can do better this time.
> 
> The [Nashville number system](https://en.wikipedia.org/wiki/Nashville_number_system) (NNS) is a way of writing chord charts by scale degree — very similar to the roman numeral style, but using Arabic numerals, optionally using a dash or lowercase 'm' to indicate minor chord, and with some additional symbols to represent rhythm.
> 
> The bass notes of slash chords are represented the same way as the rest of the chords. Here's an example that will hopefully make it clearer what I was trying to accomplish. The flow is original original key => nashville => new key.
> 
> ### Code
> ```js
> const originalChords = ['D/F#', 'G', 'D/F#', 'G/B', 'D/A', 'D/F#', 'G', 'D/F#', 'Em7', 'A', 'D']
> const nashville = originalChords.map(chord => toNashville(chord, 'D'))
> const keyOfG = nashville.map(chord => fromNashville(chord, 'G'))
> 
> 
> console.log(`Original  =>   ${originalChords.join(",  ")}`)
> console.log(`Nashville =>   ${nashville.join(",  ")}`)
> console.log(`Key of G  =>   ${keyOfG.join(",  ")}`)
> ```
> 
> ### Output
> ```
> Original   =>   D/F#,  G,  D/F#,  G/B,  D/A,  D/F#,  G,  D/F#,  Em7,  A,  D
> Nashville  =>   1/3,   4,  1/3,   4/6,  1/5,  1/3,   4,  1/3,   2m7,  5,  1
> Key of G   =>   G/B,   C,  G/B,   C/E,  G/D,  G/B,   C,  G/B,   Am7,  D,  G
> ```
> 
> Thanks so much for all the work you've put in to this, @danigb. It really shows, and I, for one, really appreciate it!

@derBingle Did you ever end up building a system to translate to/from NNS on top of tonal? I'm looking to build the same thing, and would love to hear if that's something you ended up finishing!

**Comment by der-bingle** [comment]
> @derBingle Did you ever end up building a system to translate to/from NNS on top of tonal? I'm looking to build the same thing, and would love to hear if that's something you ended up finishing!

@gabergg Today I go to solve the same problem and find my issue from three years ago w/ your comment from 5 days ago! 

I did come up with a solution based on the huge progress @danigb has made with the library in the last 3 years. All I did was adapt `progression.toRomanNumerals` function to convert those roman numerals to arabic numbers using [`big-roman`](https://www.npmjs.com/package/big-roman).

```javascript
const { distance, interval } = require("@tonaljs/core")
const { tokenize } = require("@tonaljs/chord")
const { get } = require("@tonaljs/roman-numeral")
const { romanToNumber } = require('big-roman')

let toNumbers = (key, chord) => {
    const [note, chordType] = tokenize(chord);
    const intervalName = distance(key, note);
    const roman = get(interval(intervalName));
    return romanToNumber(roman.roman) + chordType;
}
```
And then a simple function to add support for slash chord notation...
```javascript
let toNashville = (key, chord) => {
  if (chord.includes("/")) {
    let split = chord.split("/")
    return `${toNumbers(key, split[0])}/${toNumbers(key, split[1])}`
  }
  return toNumbers(key, chord)
}
```
And now `["E", "E/G#", "A", "F#m", "B", "E"]` returns `[ '1', '1/3', '4', '2m', '5', '1' ]`

Hope that helps!

**Comment by danigb** [comment]
Nice! 👌 🎉 

Maybe it can be wrapped in a module? 🤔 

One little thing. `RomanNumeral.get("IV").step + 1` is the same as `romanToNumber("IV")` so no external libraries are required

**Comment by gabergg** [comment]
> > @derBingle Did you ever end up building a system to translate to/from NNS on top of tonal? I'm looking to build the same thing, and would love to hear if that's something you ended up finishing!
> 
> @gabergg Well this is ironic... today I go to solve the same problem and find my issue from three years ago w/ your comment from 5 days ago!
> 
> I did come up with a solution based on the huge progress @danigb has made with the library in the last 3 years. All I did was adapt `progression.toRomanNumerals` function to convert those roman numerals to arabic numbers using [`big-roman`](https://www.npmjs.com/package/big-roman).
> 
> ```js
> const { distance, interval } = require("@tonaljs/core")
> const { tokenize } = require("@tonaljs/chord")
> const { get } = require("@tonaljs/roman-numeral")
> const { romanToNumber } = require('big-roman')
> 
> let toNumbers = (key, chord) => {
>     const [note, chordType] = tokenize(chord);
>     const intervalName = distance(key, note);
>     const roman = get(interval(intervalName));
>     return romanToNumber(roman.roman) + chordType;
> }
> ```
> 
> And then a simple function to add support for slash chord notation...
> 
> ```js
> let toNashville = (key, chord) => {
>   if (chord.includes("/")) {
>     let split = chord.split("/")
>     return `${toNumbers(key, split[0])}/${toNumbers(key, split[1])}`
>   }
>   return toNumbers(key, chord)
> }
> ```
> 
> And now `["E", "E/G#", "A", "F#m", "B", "E"]`
> returns `[ '1', '1/3', '4', '2m', '5', '1' ]`
> 
> Hope that helps!

Awesome timing, and a great solution! I hadn't actually seen the `roman-numeral` module.  Thanks so much! And thanks @danigb for all the work & the library!

**Comment by maartenverheul** [comment]
Any updates on this? I think it's such an important part of a chord library.
If not, maybe update the [README](https://github.com/tonaljs/tonal/blob/d86d0adb284fb899f0bdfd157b5a2431a28e9943/packages/chord/README.md?plain=1#L65) :)
