### ISSUE TITLE
Get 7 chords for a given scale 

### ISSUE THREAD

**Issue by Aduffy** [tonaljs/tonal#240]
with the Key.majorKey function a list of the seven chords for that key are provided in the chords property such as 

```
chords: [
    "Cmaj7",
    "Dm7",
    "Em7",
    "Fmaj7",
    "G7",
    "Am7",
    "Bm7b5"
],
```

With one each rooted off each note of the scale. 

Can the same thing be gotten for a given scale such as C dorian 
I have tried  Scale.get("C dorian ") but it does not provide an equivalent

**Comment by danigb** [comment]
Yes, this is because four notes triadic chords are not a property of every scale. Anyway, keep this open to see what alternatives we could figure it out. 

For example, I can imagine a function that given the chord degrees, it returns the note names. Something like:
```
Scale.getDegrees("C major", [1, 3, 5, 7]) // => ['C', 'E', 'G', 'B']
```

Thoughts?

**Comment by danigb** [comment]
Fixed by https://github.com/tonaljs/tonal/commit/b93c66f42b60e52bf3fd9817e7e9dab76d4f7c80

See `Scale.degrees` function: https://github.com/tonaljs/tonal/tree/main/packages/scale#scaledegreesscalename-string--degree-number--string
