### ISSUE TITLE
C Romanian minor notes are C,D,Eb,Gb,G,A,Bb instead of C,D,Eb,F#,G,A,Bb 

### ISSUE THREAD

**Issue by mbonnefond** [tonaljs/tonal#246]
Hi,

The C romanian minor notes should be C,D,Eb,**F#**,G,A,Bb but expression Scale.get("C romanian minor").notes returns C,D,Eb,**Gb**,G,A,Bb

See : [https://codesandbox.io/s/wrong-notes-in-tonaljs-library-forked-otijm](url)

Regards

**Comment by danigb** [comment]
Yes, you're right 👉 https://en.wikipedia.org/wiki/Ukrainian_Dorian_scale
