### ISSUE TITLE
Abc notation bug in the 0 octave. 

### ISSUE THREAD

**Issue by glend1** [tonaljs/tonal#255]
using the Abc notation converter I have found that notes in the 0 octave return an empty string. this obviously isn't a huge problem since it is barely audible. but maybe something to look into.

**Comment by sashamahalia** [comment]
I wrote a fix for this, thanks for opening the issue.

https://github.com/tonaljs/tonal/pull/258

**Comment by danigb** [comment]
PR is merged. Thanks a lot @glend1 for reporting and @sashamahalia  for fixing! 🙏
