### ISSUE TITLE
@tonaljs/abc-notation deprecated by unpublished package @tonaljs/pitch-notation-abc

### ISSUE THREAD

**Issue by rzyns** [tonaljs/tonal#261]
`@tonaljs/abc-notation` says it's deprecated in its [`README.md`](https://github.com/tonaljs/tonal/blob/v4.6.0/packages/abc-notation/README.md) and suggests [`@tonaljs/pitch-notation-abc`](https://github.com/tonaljs/tonal/tree/v4.6.0/packages/pitch-notation-abc), but it appears that none of the `@tonaljs/pitch-notation*` packages are published...?

**Comment by danigb** [comment]
You're right.

**Comment by danigb** [comment]
Removed deprecation mark
