### ISSUE TITLE
Easy way to get notes with octave of chords of scale from tonic?

### ISSUE THREAD

**Issue by majonathany** [tonaljs/tonal#279]
Hi,

This library is amazing. I actually spent a few Saturdays thinking about this to learn TypeScript to make my own web app, and came up with a Scale, Note and Chord class, not realizing this library does the same, lol. Made a whole bunch of logic for calculating enharmonics, taking a scale name and spitting out a chord list, etc. And then I find your library does the same things, haha.

Maybe I could contribute, someday. Right now I'm trying to use ToneJS to get the same quality of music output that virtualpiano.net produces, but with only notes of a specific user-defined scale visible.

I was wondering if there was an easy way to pass in a note with an octave, like "C5", and get back all the notes of the chords for the scale in absolute terms. I do know that this works:
```
    const chords = Key.majorKey("Db");
    chords.chords.map(chord =>
        console.log(Chord.get(chord).notes.slice(0,3)));
```

But this discards the octave, which I would need, to play the note in ToneJS. I could write a function to generate the octave offsets that cut off at C but since the library already has a transpose function, I was wondering if there a function that exists that already takes a single with octave, and spits out a set of notes, along with the octave.

**Comment by danigb** [comment]
I don't think we have that function inside Tonal. How do you imagine that function (signature) and what is the expected output?

**Comment by danigb** [comment]
This is now possible. In latest version you can write:

```js
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(t.Chord.degrees('Db4M'))
=> [
  'Db4', 'F4', 'Ab4',
  'Db5', 'F5', 'Ab5',
  'Db6', 'F6', 'Ab6',
  'Db7'
]
```
See https://github.com/tonaljs/tonal/tree/main/packages/chord#chorddegreeschordname-string--degree-number--string

Hope it helps
