### ISSUE TITLE
doc bug in /chord-detect

### ISSUE THREAD

**Issue by multimanic** [tonaljs/tonal#289]
This page
https://github.com/tonaljs/tonal/tree/main/packages/chord-detect
says:

With ES6 import:
`import { ChordDetect } from "@tonaljs/tonal";`
and then use it like
`ChordDetect.detect(["D", "F#", "A", "C"]); // => ["D7"]`

In practice this gives me an error message saying
`'ChordDetect' is not exported from '@tonaljs/tonal'.`

What works is this:

 With ES6 import:
`import { Chord } from "@tonaljs/tonal";`
and then use it like
`Chord.detect(["D", "F#", "A", "C"]); // => ["D7"]`

Is this a doc bug?

**Comment by danigb** [comment]
I'd say so... There are some inconsistencies about what modules are exposed and how... this is one of it...

**Comment by katerlouis** [comment]
can confirm the issue
