### ISSUE TITLE
Major triad symbol inconsistency

### ISSUE THREAD

**Issue by janwillemtulp** [tonaljs/tonal#290]
Hi,

When I do `Chord.getChord('maj7', 'C4')` I get proper results, but when I do `Chord.getChord('maj', 'C4')` I get an empty result. It turns out for a major triad I need to do `Chord.getChord('M', 'C4')`

I would say that `maj7` and `M` is a kind of symbolic inconsistency. I guess accepting `M` for major triad should still work as is, but I would expect that `maj` should work as well, espcially compared to `maj7`.

Thanks!

**Comment by danigb** [comment]
Yes, I think you're right. From wikipedia 👇 
<img width="643" alt="Screenshot 2022-02-03 at 16 55 03" src="https://user-images.githubusercontent.com/7457/152378900-ea71ed24-8aed-4df1-86d3-855f855b61c9.png">
 
I'll create a PR to fixit
