### ISSUE TITLE
Chord Progressions only for Major keys

### ISSUE THREAD

**Issue by NickToye** [tonaljs/tonal#302]
First of all, love the library - really useful.

However, there doesn't seem to be a chord progression from say 'Am'.  Or have I missed something?

**Comment by danigb** [comment]
Thanks! 

Don't know what you mean... if I remember correctly, there's no chord progression dictionary. Only some functions to do calculations like the following:

```js
> Progression.fromRomanNumerals('A', ['Im', 'IIm7b5', 'V7'])
[ 'Am', 'Bm7b5', 'E7' ]
```

**Comment by NickToye** [comment]
Of course.  Sorry, feel free to close.
