### ISSUE TITLE
Getting some unexpected note names for some scales

### ISSUE THREAD

**Issue by thisisseb** [tonaljs/tonal#325]
Using the Scale module, I seem to be getting some unexpected note names for certain scales.

For example, with:
```
Tonal.Scale.get('C whole tone').notes 
```

I get **[ "C", "D", "E", "F#", "G#", "Bb" ]**, but was expecting the last note to be noted as `A#`.

Similarly, with:
```
Tonal.Scale.get('Db whole tone').notes 
```

I get **[ "Db", "Eb", "F", "G", "A", "Cb" ]**, but was expecting a `B` instead of a `Cb`.

I've also noticed instances where I get note names with double sharps, like `F##`, while the expected note name is `G`.

They are enharmonic equivalent note names, and so they really are the same, but I'm wondering if there would be a workaround or an easy fix around these to get more expected note names.

Thanks so much!

**Comment by danigb** [comment]
You're right (reference: https://en.wikipedia.org/wiki/Whole-tone_scale). I'll fix it in next release
