### ISSUE TITLE
Chord.detect unexpected results for simple detection Cmajor

### ISSUE THREAD

**Issue by lidoravitan** [tonaljs/tonal#331]
```javascript Chord.detect(['C', 'E', 'G']) ==> [ 'CM', 'Em#5/C' ]```

what Am i missing?

**Comment by ashleymays** [comment]
I'm not sure if you've already had your question answered, but I'll just say that I think these results are fine. "CM" stands for C Major, and "Em#5/C" looks weird, but it's just an E minor with a "C" instead of a "B", and that "C" becomes the root of the chord. So it's the same as a C Major.
