### ISSUE TITLE
Tonal is not defined 

### ISSUE THREAD

**Issue by daverees4** [tonaljs/tonal#345]
My implementation of Tonal has recently broken - I'm sure it was working before! 

`Uncaught ReferenceError: Tonal is not defined`

So trying to create the simplest html page, I'm still getting the same error:  

```
<html>
  <head>
<script src="https://cdn.jsdelivr.net/npm/tonal/browser/tonal.min.js"></script>
<script>
  console.log(Tonal.Key.minorKey("Ab"));
</script>
  </head>
  <body>
  </body>
</html>

```

**Comment by 5paceb0i** [comment]
I have been facing the same issue since 2 days. I tried to change the scripts and all, but nothing worked

**Comment by daverees4** [comment]
I was able to fix by falling back to the previous version. In this version
the global Tonal object isn't created as before.

**Comment by 5paceb0i** [comment]
How did you get the previous version min.js file

**Comment by daverees4** [comment]
***@***.******@***.***/browser/tonal.min.js

**Comment by 5paceb0i** [comment]
***@***.******@***.***/browser/tonal.min.js

This isn't working. Am I missing something?

**Comment by daverees4** [comment]
Sorry the above link came out really messed up. Try this:

https://cdn.jsdelivr.net/npm/@tonaljs/tonal@4.6.5/browser/tonal.min.js

**Comment by 5paceb0i** [comment]
Hey thank you so much. My project is going to be presented at a fair in few days & was freaking out as site stopped working today.
Thanks a bunch ✨

**Comment by daverees4** [comment]
We both kind of messed up by just using the latest version of the library
and not using dependency version control!

**Comment by daverees4** [comment]
Also would be keen to see you project! We're probably working on similar
things.

**Comment by 5paceb0i** [comment]
Yeah, a point to remember next time.
You can see my project here: https://rippple.netlify.app/

**Comment by daverees4** [comment]
Very cool!

**Comment by danigb** [comment]
Yes, providing a browser version of tonal is probably not a good idea nowadays. Probably it would be better to use one service (so it's probably that I remove that in next major version). 

In a quick look, it seems the `https://esm.run/tonal` is a good alternative for esm (and deno) compatible modules, but I'm unsure about `<script ... >` tags. Thoughs?

Anyway, very cool project @5paceb0i  Have you considered to add it to the main README?
