### ISSUE TITLE
memory leak in note function

### ISSUE THREAD

**Issue by felixroos** [tonaljs/tonal#347]
Hey! I noticed that when doing a lot of note operations over a longer period of time, the browser heap memory grows and grows. After digging through heap snapshots, I found the note cache littered with objects. Because [strudel](https://strudel.tidalcycles.org/) makes heavy use of this lib, the heap happens to creep to over 100MB in a matter of minutes, compared to ~10MB without using tonal functions.

Example of a problematic call stack:

`Note.transpose("A", "3m")` -> `coordToNote([0])` -> `note({step: 0, alt: 0, dir: undefined })`

The cache inside the `note` function works like this:

```js
const cache = new Map();

/* .. */
function note(src) {
    const cached = cache.get(src);
    if (cached) {
        return cached;
    }
    const value = /* .. */
    cache.set(src, value);
    return value;
}
```

Now the problem is that `cache.get({ /* .. */ })` will always be undefined. Try running this in the browser console:

```js
const cache = new Map();
cache.set({ foo: true }, 'hello');
cache.get({ foo: true}); // undefined
```

The memory leak happens with `cache.set(src, value);`, making sure the object stays in memory until forever.

An easy fix would be to skip the cache logic when `src` is an object.

**Comment by manniL** [comment]
Instead of not using the cache, one could also stringifying the object before using it as map key 😋

**Comment by danigb** [comment]
Thanks @felixroos for reporting and @manniL for fixing 🙌 

New version 4.7.0 is released (I've messed up with the numbers and used a minor version instead a fix version 🤷 )

**Comment by felixroos** [comment]
thanks for the quick release! For some reason, `@tonaljs/core` is still on [4.6.11](https://www.npmjs.com/package/@tonaljs/core), which does not seem to contain the fix, see https://unpkg.com/browse/@tonaljs/core@4.6.11/dist/index.mjs (line 54), same for the .js version..  maybe npm needs some time, will check again tomorrow

**Comment by danigb** [comment]
Yes, I've just seen that everything got a new version except core 🤦  I'll fix it later... Meanwhile, I was never happy with the cache at all... it's a performance improvement without any proper research (for example, I'm not sure if JSON.stringify is slower that the string parse I use...) ... So in short: I was thinking into removing cache completely... what do you think?

**Comment by manniL** [comment]
I guess the cache could also be implemented in userland and allow more fine-grained control. So yes, why not removing it completely and leave it up to the user? 😋

**Comment by felixroos** [comment]
@danigb I just learned about [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) and immediately thought of this issue, because WeakMaps won't create a memory leak when a reference is used as key, so the garbage collector will kick in, even if the key is an object.. replacing all cache Maps WeakMaps is probably a better solution, because JSON.stringify is not required

**Comment by danigb** [comment]
Hey @felixroos thanks a lot for the suggestion. 🙏  

But... 🤔  I think WeakMap doesn't work in this case... The goal is to avoid some potential-expensive operations (as parsing)  by caching the result object. As far as I know (I could be wrong) weak map stores the object as long as there is a reference to the object. But, I think, is quite normal (for tonal "clients") not to store the note reference, so the cached value would be lost from one invocation to another... Am I missing something?

**Comment by felixroos** [comment]
hm yes you're probably right, using WeakMaps would mean recalculating stuff after the GC kicked in.. I am not sure how often the garbage collector will free those WeakMaps. I did a quick test with strudel, using a more tonal heavy example, and the major gc triggers roughly every 4s, while minor gc triggers much more often (~50ms). I know too little about memory to know if WeakMaps will only be cleared in a major or minor gc..

**Comment by danigb** [comment]
Still have memory issues with tonal in strudel? I can help to fix if you tell me how to reproduce them...

**Comment by felixroos** [comment]
no everything is fine now, the gc keeps things consistent :) I just discovered WeakMaps and thought I'd share it
tonal is happily running inside of it ! https://strudel.tidalcycles.org/?-G2kYRhtN-nf
