### ISSUE TITLE
Triads in key

### ISSUE THREAD

**Issue by senner007** [tonaljs/tonal#357]
Hi.

Is there any reason why the triads were removed from the Key package?
like 
`Key.majorKey("C").triads`

**Comment by senner007** [comment]
Ah yes I see.
I'm thinking about how to easily get the triad chords and their inversions for a given key. 

Lets say I have this :
`Chord.detect(["E", "G", "C"]) // ["Em#5", "CM/E"]`
Then if I have the names of all the triad chords and their inversion names in C in a list, then I can pick the most appropriate chord symbol.

**Comment by doingweb** [comment]
Also interested in this. It was surprising to this casual musician that `tonal.Key.majorKey('C').chords` didn't include any of the triads I would recognize from, say, a circle of fifths :)

**Comment by danigb** [comment]
Added. See docs: https://github.com/tonaljs/tonal/tree/main/packages/key#majorkeytonic-string--majorkey
