### ISSUE TITLE
Tonal is not defined

### ISSUE THREAD

**Issue by jlbocquet** [tonaljs/tonal#361]
Here is my source code (as specified in the usage page)
![code](https://user-images.githubusercontent.com/42833448/210241310-67641ac1-d821-43e9-8b0c-6346325fcd81.png)

I get the following error :
![error](https://user-images.githubusercontent.com/42833448/210241524-07e30d58-5712-402e-bab6-1a87a30bee6a.png)

Did i missed something ?

**Comment by tschwarzl** [comment]
Same error here

**Comment by danigb** [comment]
This should be fixed. If still not working, use the specific version instead:

```html
<script src="https://cdn.jsdelivr.net/npm/tonal@4.8.1/browser/tonal.min.js"></script>
```

You can test it by opening a blank page (write `about:blank` in the url) and writing into the development console:

```js
document.write("<script src='https://cdn.jsdelivr.net/npm/tonal@4.8.1/browser/tonal.min.js'></script>");
```
