### ISSUE TITLE
`Scale.scaleNotes` returns an array instead of a pcset.

### ISSUE THREAD

**Issue by elsherbini** [tonaljs/tonal#380]
https://github.com/tonaljs/tonal/blob/9bb921aa7df45559b909cc5ce1894d9db8bd7839/packages/scale/index.ts#L197-L213

Also, Pcset doesn't have support for a tonic, so I guess its not really possible to return a pcset with the specified tonic as the comment suggests.

https://github.com/tonaljs/tonal/blob/9bb921aa7df45559b909cc5ce1894d9db8bd7839/packages/pcset/index.ts#L27-L33

**Comment by danigb** [comment]
Don't understand exactly what is the problem to solve. The documentation says that it returns an array of notes:  `Scale.scaleNotes(notes: string[]) => string[]` but also, conceptually, that collection of notes is a pitch class set, but not a pitch class set structure.

Any ideas on how to improve both code or docs are welcomed.

**Comment by elsherbini** [comment]
Got it. I read it expecting it to return an actual scale or Pcset structure that had the properties intervals, tonic, etc. 

I was looking for some way in the library to define an arbitrary scale and get the intervals relative to the tonic without having to do everything relative to C, and reading the description I thought this was it!

So documentation-wise for this issue, maybe the description could be written:

"Given an array of notes, return an array of sorted note names starting from the first note name of the input array."

What do you think?
