### ISSUE TITLE
Exact versions

### ISSUE THREAD

**Issue by senner007** [tonaljs/tonal#408]
Hi, :)

Tonal package.json does not install exact versions of sub-packages. 
Example :
installing  "@tonaljs/tonal": "4.8.0"
installs version 4.8.1 of Scaletypes packages which breaks my code.

Is this intended?

**Comment by danigb** [comment]
If 4.8.1 breaks your code is a bug. I'll fix it

**Comment by senner007** [comment]
It's not a bug. It's just a different version

**Comment by danigb** [comment]
Yes, I mean: if a minor or fix version change breaks the code is a bug. It should be compatible (that's why versioning).

Versions are not fixed to avoid publishing all packages on every small change.

what is the problem exactly?

**Comment by senner007** [comment]
My point is that the user should be able to set a fixed version (without the ^) and expect nothing to have changed, don't you agree?

With a fixed version : "@tonaljs/tonal": "4.8.0" , the Scaletypes package is still updated

**Comment by danigb** [comment]
Yes, maybe you're right 🤔

**Comment by danigb** [comment]
Starting from version 5.2.1 dependencies are now fixed. Thanks for bring this issue 👍
