### ISSUE TITLE
[question] Convert PcSet to Scale

### ISSUE THREAD

**Issue by kubawolanin** [tonaljs/tonal#53]
Hello @danigb,
Thank you for this amazing library!
Very impressive piece of work.

Is there a way to convert a list of notes to a scale?
e.g. I have the following array:
```
["a", "c", "e", "g"]
```

and what I'd like to achieve is
```
["A4", "C5", "E5", "G5"]
```

Thank you again!

**Comment by danigb** [comment]
Hi!,

The solution is harder than I thought:

```js
const Tonal = require('tonal');

const notes = ['a', 'b', 'e', 'g'];
const intervals = PcSet.intervals(PcSet.chroma(notes)));
const scale = intervals.map(Tonal.transpose('A4'))
```

One problem is that `PcSet.intervals` doesn't accept the note array directly (but the documentation says it can). I'll keep the issue open while deciding what to do.

I hope it helps.
Suggestions and PR welcomed.

**Comment by kubawolanin** [comment]
Hey @danigb!

Thank you for the quick response.

Pasting the following code
```
var tonal = require("tonal")

const notes = ['a', 'b', 'e', 'g'];
const intervals = tonal.PcSet.intervals(tonal.PcSet.chroma(notes));
const scale = intervals.map(tonal.transpose(`${notes[0]}4`)); // same with 'A4'
```

to [RunKit](https://npm.runkit.com/tonal) gives me this result:
```
Array (4 items)
0: "C#5"
1: "E5"
2: "F#5"
3: "G#5"
```

**Comment by danigb** [comment]
True! It works with `["a", "c", "e", "g"]` but not with `['a', 'b', 'e', 'g']`. I'll investigate the issue...

**Comment by danigb** [comment]
This works and it's a better alternative:  

```
var tonal = require("tonal")

const notes = ['a', 'b', 'e', 'g'];
const intervals = notes.map(tonal.interval(notes[0]))
intervals.map(tonal.transpose(`${notes[0]}4`))
```
