### ISSUE TITLE
[question] Why is 'Major' represented as 'Maj' in some cases and 'M' in others?

### ISSUE THREAD

**Issue by JakeIwen** [tonaljs/tonal#54]
I am trying to use `Chord.supersets()` to generate a list of subnames  that produce computable chord names when joined into a string. 

I would expect, for example,  `'AMaj7'` to give `'AMaj7add13'` as a subset. Removing the original chord from this string leaves me with `'add13'` which would be used to populate a select-button. 

But `'AMaj7add13'` is actually `'AM7add13'` in the tonal library. 

Wondering if this was done for any reason besides brevity...

I'm considering forking and having `'Maj'` be the only representation used. Do you forsee any complications with this? 

Fantastic work, thank you for this awesome contribution to npm!

**Comment by danigb** [comment]
Great! A PR will be highly appreciated

**Comment by danigb** [comment]
Chord dictionary revamp at v3. Hope it's now fixed.
