### ISSUE TITLE
tokenize doesnt recognize 5 and below

### ISSUE THREAD

**Issue by walmik** [tonaljs/tonal#70]
Hi @danigb I was using this method `Tonal.Chord.tokenize('C4')` and realized that `tokenize` doesnt recognize 5 and below. Something like `Tonal.Chord.tokenize('C6')` or `Tonal.Chord.tokenize('E7')` works fine and returns `['C', '6']` and `['C', '7']` respectively. But `Tonal.Chord.tokenize('C4')` returns `['C4', '']`

Is this by design?

I m currently allowing users of my module to use a combination of notes and chords together. For e.g. `'CMaj7 D3 Cm-4 C4 C4th'` Here `-4` defines the octave and `C4` is the note `C4` and `C4th` gets converted to `C4` chord and send for tokenization. Please let me know if the 5 and below are not recognized by design. If so, then i ll add some hack around those.

**Comment by danigb** [comment]
It looks so from the source:

```
// 6, 64, 7, 9, 11 and 13 are consider part of the chord
// (see https://github.com/danigb/tonal/issues/55)
const NUM_TYPES = /^(6|64|7|9|11|13)$/;
```

References #55 

But I'm open to suggestions (and PRs!)

**Comment by walmik** [comment]
Thank you for such a fast response! 

Ideally 4 and 5 are valid chords (and are also available here https://danigb.github.io/tonal-app/#/C/chords) It would be nice to have support for at least for these in the `tokenize` method. I can create the PR if you are open to the suggestion.

**Comment by walmik** [comment]
This may not be the best way but how bout have users reference such chords with a suffix like `C7th` and spell it out clearly in the documentation. Given the nature of the problem, it may not be entirely despicable.
