### ISSUE TITLE
Chords detection bug (maybe?)

### ISSUE THREAD

**Issue by DvDream** [tonaljs/tonal#86]
Hi, I don't understand why considering whatever chord except from Cmaj7 (I tested some chords), the function chord() returns different chords (the inversions) but the tonic of the sequences of notes that I put in is ALWAYS in the second position..is it a bug or am I doing something wrong? 
Is there moreover a way to have always the same name of a chord without considering the inversions, so I can put notes in whatever order I want? Thanks in advance for the answers!

here some examples:

console.log(Chord.notes("Dm7")) // ["D", "F", "A", "C"]
console.log(chord(["D","**F**","A","C"])); // ["Fm7"] 
console.log(chord(["F","**A**","C","D"])); //  ["Am7"]
console.log(chord(["A","**C**","D","F"])); // ["Cm7"]
console.log(chord(["C","**D**","F","A"])); // ["Dm7"]

console.log(Chord.notes("Emaj7")) //  ["E", "G#", "B", "D#"]
console.log(chord(["E","**G#**","B","D#"])); //["G#Maj7"] but I should expect Emaj7
console.log(chord(["G#","**B**","D#","E"])); //["BMaj7"] but I should expect G#Maj7
console.log(chord(["B","**D#**","E","G#"])); //["D#Maj7"] but I should expect BMaj7
console.log(chord(["D#","**E**","G#","B"])); //["EMaj7"] but I should expect D#maj7

**Comment by danigb** [comment]
Here: https://github.com/tonaljs/tonal/tree/master/packages/chord-detect
