### ISSUE TITLE
interval/README.md issue

### ISSUE THREAD

**Issue by tobx** [tonaljs/tonal#93]
Hi, awesome work. I was just a bit confused about the `interval/README.md` file until I realized that the contents under a headline belongs to the next headline. Something seems to be shifted: e.g. under `Interval.num(interval) ⇒ String` you find the explanation of `Interval.name(ivl)`.

**Comment by glhrmv** [comment]
I think this brings up something I thought of the other day: is there even a need for multiple points of entry for the API documentation? One would expect the [live API docs site](http://danigb.github.io/tonal/) to be the central (and hopefully only) authority on it but as we can see from this issue, people are finding inconsistencies and errors and it's not made clear where to go to fix this problem. I can't even find the documentation for the `Interval` module in the live site, for some reason.

**Comment by danigb** [comment]
You are right! Currently, there are too many documentation resources and `Invertal` module is not present (I don't know why)... Do you have any suggestions? Also PR are welcomed...

**Comment by glhrmv** [comment]
My suggestion to fix this immediate issue would be to use only the central `tonal` module to generate documentation and have the live API site always reflect the latest version. This way you could get rid of the `docs` script in each of the packages that generates the respective module's docs to its README file.

I think it would also be worth merging the extensions with all of the packages. I don't know what the decision behind splitting them up was initially but I think it makes the whole process simpler from the end-user perspective to have everything loaded up (and exported from the `Tonal` module) on install. 

I would like to contribute to this library, and I forked it a while ago but I have no experience with Lerna or Typescript (or really any project of this scale) so I've been hesitant to make any big changes.

**Comment by danigb** [comment]
Hi @glhrmv!

Thanks a lot for the feedback. I answer inline:

> My suggestion to fix this immediate issue would be to use only the central `tonal` module to generate documentation and have the live API site always reflect the latest version. This way you could get rid of the `docs` script in each of the packages that generates the respective module's docs to its README file.

I've recently removed the docs folder. And yes, I'd be really nice that docs always reflect the latest version, but I didn't find a way to _automate_ this. 

The "source of truth" is the source files itself, where all jsdoc is written. Currently, there are two versions: the README.md and the official docs: http://danigb.github.io/tonal/. I don't know why Interval is not listed there (I'll take a look to that issue)

> I think it would also be worth merging the extensions with all of the packages.

Agree. On my TODO list.

> I would like to contribute to this library, and I forked it a while ago but I have no experience with Lerna or Typescript (or really any project of this scale) so I've been hesitant to make any big changes.

Yes, I'm not happy with the infrastructure. Too complex for this kind of project... But I don't know how to simplify it without losing the ability to have single packages for each module.

**Comment by glhrmv** [comment]
Not sure how it's been already 3 days since I commented that, time is wild.

I think the main issue with keeping docs separate is it might hinder working with more than one Tonal module. With one source of reference in the same website, a developer using `tonal` can just always go back to it for all of their Tonal needs. If they are split up (i.e., if the official docs site did not exist), developers would need to keep track of all of the repos and READMEs for all of the modules they need, and I can see that quickly becoming frustrating.

I don't know how you're currently updating the contents of the site, but from what you said I'm assuming Lerna does not have a way to run a script that goes through all subprojects in your umbrella? That's a pretty big issue, if so. It seems like a common use case.

**Comment by danigb** [comment]
Now documentation is handwritten. Hope it's everything clear now.
