### ISSUE TITLE
Tonal v3 - ¿Remove lerna and tonal packages?

### ISSUE THREAD

**Issue by danigb** [tonaljs/tonal#95]
Currently, [lerna](https://lernajs.io/) is used to create tonal sub-packages like `tonal-note` or `tonal-interval`. But this makes project setup very complex and it's a big entry barrier for people to contribute.

Before ES6, having sub-packages made sense, to reduce the bundle size. But now we have tools that perform treeshacking efficiently.

So my idea is to radically simplify the project structure and provide something like:

```js
import Note from "tonal/note"
```

Instead of:
```js
import Note from "tonal-note";
```

The Tonal facade would work the same:

```js
import Tonal from "tonal";

// or
import { Note } from "tonal";
```

Having a simple and friendly development environment I think is more important than keep sub-packages.

What do you think?

**Comment by glhrmv** [comment]
I'm all for reducing third party dependencies and using as many standard features as possible. 👍

**Comment by danigb** [comment]
Well... finally I didn't remove lerna... 😢 but I removed javascript! 😱

v3 is published and uses lerna and typescript, but the setup has been greatly simplified. IMO, the library (code and infrastrcture) is far more developer friendly.
